### ISSUE TITLE
win: package is uploaded but ci reports errors

### ISSUE THREAD

**Issue by looooo** [conda-forge/libredwg-feedstock#35]
windows is failing with:
```
Uploaded D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp93z_ajju\\binstar.token'.  Trying again in 1 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp5ti0f205\\binstar.token'.  Trying again in 4 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpav6psky1\\binstar.token'.  Trying again in 25 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpe7_7bxvp\\binstar.token'.  Trying again in 36 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp8qb9lp17\\binstar.token'.  Trying again in 49 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp796bi0md\\binstar.token'.  Trying again in 64 seconds
Distribution D:\bld\win-64\libredwg-0.10.1.3200-h946a894_0.tar.bz2 already exists for conda-forge
Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp01n9r4dr\\binstar.token'.  Trying again in 81 seconds
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\upload_package-script.py", line 10, in <module>
    sys.exit(upload_package())
  File "C:\Miniconda\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Miniconda\lib\site-packages\conda_forge_ci_setup\build_utils.py", line 141, in upload_package
    retry_upload_or_check(recipe_root, owner, channel, [config_file])
  File "C:\Miniconda\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 162, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
```
but the package is available at anaconda.org . Any ideas @conda-forge/core ?

**Comment by looooo** [comment]
This issue is still open @conda-forge/core.

**Comment by beckermr** [comment]
I'd rerender the feedstock and try again.

**Comment by looooo** [comment]
I don't think this is the case here. Normally rerenderings are done by the bot when a new version is available. So a rerenering happened recently.

**Comment by beckermr** [comment]
This upload worked - IDK why it is erroring

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=140586&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=4d53b7b9-9f37-55b4-f2bb-6fee1e431981&l=26

**Comment by beckermr** [comment]
I checked master and that upload worked just fine too but then the CI errored.
